setclipboard("https://discord.gg/JXgCz6uC2U")
game:GetService("Players").LocalPlayer:Kick(
	"Temporary Shutdown\n\n" ..
		"The script is temporarily disabled for maintenance.\n" ..
		"Please join our Discord server.\n" ..
		"(Discord link has been copied to your clipboard)\n\n" ..
		"ขณะนี้สคริปต์ถูกปิดปรับปรุงชั่วคราว\n" ..
		"โปรดเข้าร่วมดิสคอร์ดของเรา\n" ..
		"(ลิงก์ดิสคอร์ดถูกคัดลอกไปยังคลิปบอร์ดแล้ว)"
)
